-- =====================================================
-- MIGRATION: 20260312_add_slug_to_services
-- Description: Adds a slug column to the services table
-- =====================================================

BEGIN;

-- Add slug column. It's not globally unique because different tenants can have the same service slug.
-- It must be unique per tenant_id.
ALTER TABLE services ADD COLUMN IF NOT EXISTS slug TEXT;

-- Create a unique constraint for tenant_id and slug
-- but first, we need to populate existing rows to avoid constraint violations if there are any conflicts, 
-- or we can just allow nulls temporarily.
-- For safety, we will allow nulls for now and generate slugs for existing services.

UPDATE services
SET slug = lower(regexp_replace(name, '\s+', '-', 'g'))
WHERE slug IS NULL;

-- If there are duplicates generated by the simple replace above within a tenant, the unique index creation might fail.
-- Let's try to add the unique index safely (will fail if duplicates exist)
-- A more robust approach would be handling duplicates manually later, but for now we expect no duplicates.
CREATE UNIQUE INDEX IF NOT EXISTS idx_services_tenant_slug ON services(tenant_id, slug);

COMMIT;
